In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('/content/sample_data/heart1.csv')

In [ ]:
y = df['target']
X = df.drop(['target'], axis = 1)

In [ ]:
# Data Normalization
X = (X - X.min())/(X.max()-X.min())

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=63)

In [ ]:
#Support Vector Machines (SVM) Model
from sklearn.svm import SVC
svm = SVC(kernel='linear',C=2)
svm.fit(X_train,y_train)
pre_svm=svm.predict(X_test)
score = svm.score(X_train, y_train)
score1 = svm.score(X_test, y_test)
confusion_matrix = metrics.confusion_matrix(y_test, pre_svm)
print("\nSupport Vector Machine")
print("Confusion Matrix")
print(confusion_matrix)
print("Accuracy:",score1)


Support Vector Machine
Confusion Matrix
[[ 25  17]
 [  8 106]]
Accuracy: 0.8397435897435898


In [ ]:
#Adaboost
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier(n_estimators=50,learning_rate=1,random_state=20)
abc = abc.fit(X_test, y_test)
pre_abc=abc.predict(X_test)
score = abc.score(X_train, y_train)
score1 = abc.score(X_test, y_test)
confusion_matrix = metrics.confusion_matrix(y_test, pre_abc)
print("\nAdaboost")
print("Confusion Matrix")
print(confusion_matrix)
print("Accuracy:",score1)


Adaboost
Confusion Matrix
[[ 41   1]
 [  0 114]]
Accuracy: 0.9935897435897436


In [ ]:
from xgboost import XGBClassifier
xgb=XGBClassifier(learning_rate=1)
xgb.fit(X_train, y_train)
xgb_pre=xgb.predict(X_test)
score1 = xgb.score(X_test,y_test)
print("Accuracy:",score1)

Accuracy: 0.9358974358974359


Tuning

In [ ]:
search_space = [
  {
    'clf__n_estimators': [50, 100, 150, 200],
    'clf__learning_rate': [0.01, 0.1, 0.2, 0.3],
    'clf__max_depth': range(3, 10),
    'clf__colsample_bytree': [i/10.0 for i in range(1, 3)],
    'clf__gamma': [i/10.0 for i in range(3)],
    'fs__k': [10],
  }
]

In [ ]:
model = GridSearchCV(xgb, param_grid=search_space, cv=10, verbose=1, n_jobs=-1)

In [ ]:
model.fit(X_train,y_train)

Fitting 10 folds for each of 672 candidates, totalling 6720 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 116 tasks      | elapsed:    4.5s
[Parallel(n_jobs=-1)]: Done 716 tasks      | elapsed:   21.7s
[Parallel(n_jobs=-1)]: Done 1716 tasks      | elapsed:   50.4s
[Parallel(n_jobs=-1)]: Done 3116 tasks      | elapsed:  1.5min
[Parallel(n_jobs=-1)]: Done 4916 tasks      | elapsed:  2.4min
[Parallel(n_jobs=-1)]: Done 6720 out of 6720 | elapsed:  3.2min finished


GridSearchCV(cv=10, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=100, n_jobs=1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos...ed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=-1,
             param_grid=[{'clf__colsample_bytree': [0.1, 0.2],
                          'clf__gamma': [0.0, 0.1, 0.2],
                          'clf__learning_rate': [0.01, 0.1, 0.2, 0.3],

In [ ]:
model_pre=model.predict(X_test)

In [ ]:
score=model.score(X_test,y_test)

In [ ]:
score

0.9358974358974359

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
decitrr=DecisionTreeClassifier()
decitrr.fit(X_train,y_train)
decitrr.predict(X_test)

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1])

In [ ]:
param_dict={"criterion":['gini','entropy'], "max_depth":range(1,10), "min_samples_split":range(1,10), "min_samples_leaf":range(1,5)}

In [ ]:
grid=GridSearchCV(decitrr, param_grid=param_dict, cv=10, verbose=1, n_jobs=-1)

In [ ]:
grid.fit(X_train,y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Done 1660 tasks      | elapsed:    4.3s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   17.7s finished


GridSearchCV(cv=10, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                    

In [ ]:
grid.best_params_

{'criterion': 'entropy',
 'max_depth': 9,
 'min_samples_leaf': 1,
 'min_samples_split': 3}

In [ ]:
grid.best_estimator_

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=9, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=3,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
grid.best_score_

0.925023126734505

In [ ]:
from sklearn.ensemble import StackingClassifier

In [ ]:
estimators = [('abc',AdaBoostClassifier(n_estimators=50,learning_rate=1,random_state=20)), ('dt', GridSearchCV(decitrr, param_grid=param_dict, cv=10, verbose=1, n_jobs=-1)), ('xgb', XGBClassifier(learning_rate=1))]

In [ ]:
clf = StackingClassifier(estimators=estimators, final_estimator=SVC(kernel='linear',C=2))

In [ ]:
clf.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Done 1660 tasks      | elapsed:    4.0s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   16.4s finished


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 1784 tasks      | elapsed:    4.2s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   15.7s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Done 1660 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   15.7s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Done 1660 tasks      | elapsed:    3.9s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   15.6s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Done 1660 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   15.6s finished
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.


Fitting 10 folds for each of 648 candidates, totalling 6480 fits


[Parallel(n_jobs=-1)]: Done 1660 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done 6480 out of 6480 | elapsed:   15.6s finished


StackingClassifier(cv=None,
                   estimators=[('abc',
                                AdaBoostClassifier(algorithm='SAMME.R',
                                                   base_estimator=None,
                                                   learning_rate=1,
                                                   n_estimators=50,
                                                   random_state=20)),
                               ('dt',
                                GridSearchCV(cv=10, error_score=nan,
                                             estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                                              class_weight=None,
                                                                              criterion='gini',
                                                                              max_depth=None,
                                                                              max_features=None,

In [ ]:
clf_pre=clf.predict(X_test)

In [ ]:
clf_score=clf.score(X_test,y_test)

In [ ]:
clf_score

0.9358974358974359